name: issues

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dep
      run: |
        pip install beautifulsoup4 requests

    - name: Get Issue Info
      id: issue-info
      env:
        ISSUE: ${{toJson(github.event.issue)}}
      run: |
        ISSUE=$(echo $ISSUE | base64 --wrap=0)
        python .github/dump_info.py $ISSUE

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.issue-info.outputs.issue_number }}
        body: |
          Article:

          - article: [${{ steps.issue-info.outputs.title }}](${{ steps.issue-info.outputs.url }})
          - desc: ${{ steps.issue-info.outputs.desc }}
    # - name: Generate article
    #   id: generate-article
    #   uses: Shell32-Natsu/blog-article-from-issue-action@v1
    #   with:
    #     issueJson: ${{ steps.issue-info.outputs.issue }}
    #     authorizedUser: Shell32-Natsu
        
    # - name: Show article
    #   if: ${{ steps.generate-article.outputs.valid == 'true' }}
    #   run: echo "${{ steps.generate-article.outputs.article }}" | base64 --decode
    
    # - name: Write to file
    #   if: ${{ steps.generate-article.outputs.valid == 'true' }}
    #   run: |
    #     FILE="source/_posts/${{ github.event.issue.title }}.md"
    #     echo "${{ steps.generate-article.outputs.article }}" | base64 --decode > "$FILE"
        
    # - name: Commit and Push
    #   if: ${{ steps.generate-article.outputs.valid == 'true' }}
    #   run: |
    #     git config --global user.name 'Donny Xia'
    #     git config --global user.email 'shell32-natsu@users.noreply.github.com'
    #     git add --all
    #     git commit -am "Add article ${{ github.event.issue.title }}"
    #     git push -f
      