name: issue_comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dep
      run: |
        pip install requests

    - name: Get Issue Info
      id: issue-info
      env:
        ISSUE: ${{toJson(github.event.issue)}}
      run: |
        ISSUE=$(echo $ISSUE | base64 --wrap=0)
        echo $ISSUE
        python .github/comment.py $ISSUE

    - name: Commit and Push
      if: ${{ steps.issue-info.outputs.update == '2' }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -am "Add article ${{ github.event.issue.title }}"
        git push

    - name: Close Issue
      if: ${{ steps.issue-info.outputs.close == '2' }}
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Auto-closing this issue.
