name: issues

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dep
      run: |
        pip install beautifulsoup4 requests

    - name: Get Issue Info
      id: issue-info
      env:
        ISSUE: ${{toJson(github.event.issue)}}
      run: |
        ISSUE=$(echo $ISSUE | base64 --wrap=0)
        python .github/run.py $ISSUE

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.issue-info.outputs.issue_number }}
        body: |
          Article:

          - article: [${{ steps.issue-info.outputs.title }}](${{ steps.issue-info.outputs.url }})
          - desc: ${{ steps.issue-info.outputs.desc }}

    - name: Create comment
      if: ${{ steps.issue-info.outputs.exist == '2' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.issue-info.outputs.issue_number }}
        body: |
          exist, skip.

    - name: Commit and Push
      if: ${{ steps.issue-info.outputs.update == '2' }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -am "Add article ${{ github.event.issue.title }}"
        git push

    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Auto-closing this issue.