name: issues

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Python Dep
      run: |
        pip install beautifulsoup4 requests

    - name: Install Go Dep
      run: |
        git clone https://github.com/chyroc/lark-send-msg-cli /tmp/lark-send-msg-cli
        cd /tmp/lark-send-msg-cli && go build -o /tmp/lark-send-msg-cli-bin main.go

    - name: Get Issue Info
      id: issue-info
      env:
        ISSUE: ${{toJson(github.event.issue)}}
      run: |
        ISSUE=$(echo $ISSUE | base64 --wrap=0)
        echo $ISSUE
        python .github/run.py $ISSUE

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.issue-info.outputs.issue_number }}
        body: |
          Article:

          文章: ${{ steps.issue-info.outputs.title }}
          链接: ${{ steps.issue-info.outputs.url }}

          ${{ steps.issue-info.outputs.desc }}

    - name: Create comment
      if: ${{ steps.issue-info.outputs.exist == '2' }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ steps.issue-info.outputs.issue_number }}
        body: |
          已存在，跳过并关闭。

    - name: Commit and Push
      if: ${{ steps.issue-info.outputs.update == '2' }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add --all
        git commit -am "Add ${{ github.event.issue.title }}"
        git push

    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          已提交，关闭。

    - name: Send Message to Lark
      if: ${{ steps.issue-info.outputs.exist != '2' }}
      run: |
        /tmp/lark-send-msg-cli-bin --timeout 10 --webhook $LARK_WEBHOOK --secret $LARK_SECRET --message "文章: ${{ steps.issue-info.outputs.title }}\n链接: ${{ steps.issue-info.outputs.url }}\n\n${{ steps.issue-info.outputs.desc }}" --wrap
      env:
        LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
        LARK_SECRET: ${{ secrets.LARK_SECRET }}